esphome:
  name: esphome-web-b11440
  friendly_name: RP2350 Display Bridge
  on_boot:
    priority: -100
    then:
      - delay: 10s
      - lambda: |-
          auto time_now = id(homeassistant_time).now();
          if (time_now.is_valid()) {
            char time_str[60];
            snprintf(time_str, sizeof(time_str), "SETTIME:%d,%d,%d,%d,%d,%d,%d,%d\n",
                     time_now.year, time_now.month, time_now.day_of_month,
                     time_now.hour, time_now.minute, time_now.second,
                     time_now.day_of_week, time_now.day_of_year);
            id(uart_bus).write_str(time_str);
            ESP_LOGI("main", "Sent time to RP2350: %s", time_str);
          } else {
            ESP_LOGW("main", "Time not yet synchronized, will retry on hourly sync");
          }

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: INFO

api:
  services:
    - service: send_notification
      variables:
        title: string
        message: string
        color: string
      then:
        - uart.write:
            id: uart_bus
            data: !lambda |-
              std::string msg = "NOTIFY:" + title + ":" + message + ":" + color + "\n";
              return std::vector<uint8_t>(msg.begin(), msg.end());

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Time from Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Sync time every hour
      - seconds: 0
        minutes: 0
        then:
          - lambda: |-
              auto time_now = id(homeassistant_time).now();
              char time_str[60];
              snprintf(time_str, sizeof(time_str), "SETTIME:%d,%d,%d,%d,%d,%d,%d,%d\n",
                       time_now.year, time_now.month, time_now.day_of_month,
                       time_now.hour, time_now.minute, time_now.second,
                       time_now.day_of_week, time_now.day_of_year);
              id(uart_bus).write_str(time_str);

# UART to RP2350
uart:
  id: uart_bus
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 115200

# Text input for messages
text:
  - platform: template
    name: "Display Message"
    id: display_msg
    mode: text
    optimistic: true
    on_value:
      then:
        - uart.write:
            id: uart_bus
            data: !lambda |-
              std::string msg = "MSG:" + x + "\n";
              return std::vector<uint8_t>(msg.begin(), msg.end());

# Brightness control
number:
  - platform: template
    name: "Display Brightness"
    min_value: 0
    max_value: 100
    step: 10
    initial_value: 100
    optimistic: true
    on_value:
      then:
        - uart.write:
            id: uart_bus
            data: !lambda |-
              std::string msg = "BRIGHT:" + to_string((int)x) + "\n";
              return std::vector<uint8_t>(msg.begin(), msg.end());

# Display mode selector
select:
  - platform: template
    name: "Display Mode"
    options:
      - "Clock"
      - "Sensors"
      - "Weather"
      - "Custom"
    initial_option: "Clock"
    optimistic: true
    on_value:
      then:
        - uart.write:
            id: uart_bus
            data: !lambda |-
              std::string msg = "MODE:" + x + "\n";
              return std::vector<uint8_t>(msg.begin(), msg.end());
